Repository Coastee/COASTER-Client, pull requests merged in 2025-05, with the labels that each got.

#155 #154 [FEAT] 채팅방 강퇴 기능 구현
  src/apis/index.ts
  src/components/ProfileMenu/ProfileMenu.styles.ts
  src/components/ProfileMenu/ProfileMenu.tsx
  src/components/SideMenuBar/SideMenuBar.styles.ts
  src/components/SideMenuBar/SideMenuBar.tsx
  src/hooks/useKickOutMember.ts
  src/ky/ky.ts
  src/pages/ChatPage/apis/fetchChatMembers.ts
  src/pages/ChatPage/apis/fetchSideChatList.ts
  src/pages/ChatPage/hooks/useChatMembers.ts
  src/pages/ChatPage/hooks/useSideChatList.ts
  src/routers/Router.tsx
  src/types/index.ts
Labels: 📬 API

#163 #162 [FIX] 서버 사이드 메뉴 하단 여백 제거
  src/components/ServerHeader/components/ServerDropdown/ServerDropdown.styles.ts
Labels: 🎨 UI

#161 #160 [FIX] 레이아웃 스크롤 오류 해결
  src/styles/globalStyle.ts
Labels: 🎨 UI

#164 [MERGE] dev to main
  src/components/ServerHeader/components/ServerDropdown/ServerDropdown.styles.ts
  src/styles/globalStyle.ts
Labels: ❄️ Release

#166 #165 [FIX] 레이아웃 스크롤 오류 해결(re)
  src/styles/globalStyle.ts
Labels: 🎨 UI

#169 #168 [FIX] overflow: auto 삭제
  src/styles/globalStyle.ts
Labels: 🎨 UI
