Repository Coastee/COASTER-Client, pull requests merged in 2025-01, with the labels that each got.

#7 [FEAT] svgr setting
  package.json
  public/svg/vite.svg
  src/assets/img/.keep
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ⚙️ Setting

#5 #4 [FEAT] 피그마에 있는 디자인 시스템 적용
  public/svg/logo1Icon.svg
  public/svg/logo2Icon.svg
  public/svg/logo3Icon.svg
  src/App.tsx
  src/assets/img/.keep
  src/assets/svg/Logo1Icon.tsx
  src/assets/svg/Logo2Icon.tsx
  src/assets/svg/Logo3Icon.tsx
  src/assets/svg/Vite.tsx
  src/assets/svg/index.ts
  src/pages/HomePage/HomePage.styles.ts
  src/pages/HomePage/HomePage.tsx
  src/styles/globalStyle.ts
  src/styles/theme/theme.ts
  yarn.lock
Labels: ⚙️ Setting, 🎨 UI

#12 #11 [FEAT] 공통 Input/Textarea 컴포넌트 구현
  public/svg/rotateLogoIcon.svg
  src/assets/svg/RotateLogoIcon.tsx
  src/assets/svg/index.ts
  src/components/Input/Input.styles.ts
  src/components/Input/Input.tsx
  src/components/Textarea/Textarea.styles.ts
  src/components/Textarea/Textarea.tsx
  src/constants/placeholder.ts
  yarn.lock
Labels: ✨ Feature

#15 #13 [Feat] Divider 공통 컴포넌트 구현
  src/components/Divider/Divider.style.ts
  src/components/Divider/Divider.tsx
Labels: ✨ Feature

#23 #19 [FEAT] 회원가입 페이지 퍼블리싱
  src/components/AuthContainer/AuthContainer.styles.ts
  src/components/AuthContainer/AuthContainer.tsx
  src/components/CheckBox/Checkbox.styles.ts
  src/components/CheckBox/Checkbox.tsx
  src/components/Textarea/Textarea.styles.ts
  src/components/index.ts
  src/constants/signup.ts
  src/hooks/useFunnel.tsx
  src/pages/OnboardingPage/OnboardingPage.tsx
  src/pages/SignupPage/SignupPage.styles.ts
  src/pages/SignupPage/SignupPage.tsx
  src/pages/SignupPage/components/ContactStep/ContactStep.styles.ts
  src/pages/SignupPage/components/ContactStep/ContactStep.tsx
  src/pages/SignupPage/components/InfoStep/InfoStep.tsx
  src/pages/SignupPage/components/InterestStep/InterestStep.styles.ts
  src/pages/SignupPage/components/InterestStep/InterestStep.tsx
  src/pages/SignupPage/components/ProfileStep/ProfileStep.tsx
  src/pages/SignupPage/index.ts
  src/routers/Router.tsx
  tsconfig.json
Labels: ✨ Feature

#22 #21 [Feat] 타이틀 컨테이너 (공통 컴포넌트)
  public/svg/arrowDownIcon.svg
  src/assets/svg/ArrowDownIcon.tsx
  src/assets/svg/index.ts
  src/components/Button/Button.style.ts
  src/components/Button/Button.tsx
  src/components/Dropdown/Dropdown.styles.ts
  src/components/Dropdown/Dropdown.tsx
  src/components/TitleContainer/TitleContainer.styles.ts
  src/components/TitleContainer/TitleContainer.tsx
  src/components/index.ts
  src/constants/dropdown.ts
  src/styles/theme/theme.ts
Labels: ✨ Feature

#27 #26 [FEAT] HomePage 그룹챗 리스트 퍼블리싱
  src/assets/img/rotateLogoImg.png
  src/components/AuthContainer/AuthContainer.styles.ts
  src/components/Dropdown/Dropdown.styles.ts
  src/components/GroupChatList/GroupChatList.styles.ts
  src/components/GroupChatList/GroupChatList.tsx
  src/components/TitleContainer/TitleContainer.styles.ts
  src/components/index.ts
  src/dummy/chatRoomsDummy.ts
  src/pages/HomePage/HomePage.styles.ts
  src/pages/HomePage/HomePage.tsx
Labels: ✨ Feature, 🎨 UI
